// TEST - nastaveni sekvence ctverctu a zvirat v nich
var TestSequence = [ 
['I','F',1],
['B','H',1],
['I','C',0],
['F','D',1],
['B','A',0],
['G','H',0],
['A','F',1],
['C','H',0],
['E','A',1],
['H','D',0],
['A','E',1],
['B','G',0],
['A','H',1],
['C','B',0],
['A','C',1],
['I','F',0],
['D','C',1],
['F','A',0],
['H','B',1],
['D','A',0],
['G','E',1],
['H','G',0],
['B','F',1],
['A','D',0],
['F','C',1],
['B','D',0],
['G','H',1],
['H','F',0],
['C','D',1],
['G','B',0],
['H','C',1],
['F','G',0],
['D','E',1],
['G','A',0],
['C','I',1],
['E','H',0],
['G','D',1],
['C','A',0],
['D','B',1],
['E','G',0],
['C','F',1],
['H','G',0]
]; 
// sekvence ctvercu a cisel zvirat. Cisla zvirat jsou indexy v AnimalPositions
var DoTest = true;        // tohle rozhoduje, jestli se jedna o test nebo trening

experiment.includeScript(".//SleepForest.js");